backweb/urls.py
from django.conf.urls import url
from backweb import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^article/$', views.article, name='article'),
    url(r'^add_article/$', views.add_article, name='add_article'),
    url(r'^edit_article/(\d+)/$', views.edit_article, name='edit_article'),
    url(r'^del_article/(\d+)/$', views.del_article, name='del_article'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from blog.settings import MEDIA_URL, MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb')),
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from web import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^share/$', views.share, name='share'),
    url(r'^info/$', views.info, name='info')
]

backweb/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=12, unique=True)
    password = models.CharField(max_length=12)
    create_time = models.TimeField(auto_now_add=True)

    class Meta:
        db_table = 'user'


class AType(models.Model):
    types = models.CharField(max_length=10)
    f_typeid = models.IntegerField(null=True)

    class Meta:
        db_table = 'article_type'


class Article(models.Model):
    title = models.CharField(max_length=30, null=False)
    types = models.ForeignKey(AType, null=False, on_delete=models.CASCADE)
    desc = models.CharField(max_length=100, null=True)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    icon = models.ImageField(upload_to='article', null=True)
    is_show = models.BooleanField(default=0)

    class Meta:
        db_table = 'article'

web/models.py
from django.db import models

# Create your models here.

backweb/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from backweb.Artform import Artform, Editform
from backweb.models import User, Article


def index(request):
    if request.method == 'GET':

        return render(request, 'backweb/index.html')


def login(request):
    if request.method == 'GET':

        return render(request, 'backweb/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('userpwd')
        ob_user = User.objects
        if ob_user.filter(username=username):
            if ob_user.filter(username=username, password=password):
                request.session['user_id'] = ob_user.filter(username=username, password=password).first().id
                return HttpResponseRedirect(reverse('backweb:index'))
            else:
                err_data = '密码错误'
                return render(request, 'backweb/login.html', {'err_data': err_data})
        err_data = '账号错误'
        return render(request, 'backweb/login.html', {'err_data': err_data})
        # return render(request, 'backweb/login.html', {'err_data': err_data})


def register(request):
    if request.method == 'GET':
        return render(request, 'backweb/register.html')
    username = request.POST.get('username')
    password = request.POST.get('userpwd')
    repassword = request.POST.get('reuserpwd')
    ob_user = User.objects
    if ob_user.filter(username=username):
        err_data = '该账号已注册，请换一个账号'
        return render(request, 'backweb/register.html', {'err_data': err_data})
    if password != repassword:
        err_data = '两次密码不同！请重新输入！'
        return render(request, 'backweb/register.html', {'err_data': err_data})
    else:
        ob_user.create(username=username, password=password)
        return HttpResponseRedirect('/backweb/login/')


def article(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.filter(is_show=1)
        paginator = Paginator(articles, 3)
        pages = paginator.page(page)
        return render(request, 'backweb/article.html', {'pages': pages})


def add_article(request):
    if request.method == 'GET':
        return render(request, 'backweb/add_article.html')
    if request.method == 'POST':
        form = Artform(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            category = int(form.cleaned_data['category'])
            icon = form.cleaned_data['icon']
            Article.objects.create(title=title, desc=desc, content=content, types_id=category, icon=icon)
            return HttpResponseRedirect(reverse('backweb:article'))
        else:
            return render(request, 'backweb/add_article.html', {'form': form})


def edit_article(request, id):
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        return render(request, 'backweb/add_article.html', {'article':article})
    if request.method == 'POST':
        form = Editform(request.POST, request.FILES)
        if form.is_valid():
            # 验证成功
            title = form.cleaned_data['title']
            desc = form.cleaned_data.get('desc')
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            article = Article.objects.filter(pk=id).first()
            article.title = title
            article.desc = desc
            article.content = content
            article.icon = icon
            if icon:
                article.icon = icon
            article.save()
            return HttpResponseRedirect(reverse('backweb:article'))
        else:
            # 验证失败
            article = Article.objects.filter(pk=id).first()
            return render(request, 'backweb/article.html', {'form': form, 'article': article})

def del_article(request, id):
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        article.is_show=0
        article.save()
        return HttpResponseRedirect(reverse('backweb:article'))

web/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from backweb.models import Article, AType


def index(request):
    if request.method == 'GET':
        data = Article.objects.all()
        type = AType.objects.all()
        return render(request, 'web/index.html',{'type': type, 'data': data})
    if request.method == 'POST':
        img = Article.objects.all()
        type = AType.objects.all()
        msg = request.POST.get('keyboard')
        page = int(request.GET.get('page', 1))
        article = Article.objects.filter(title__contains=msg, is_show=1)
        paginator = Paginator(article, 20)
        pages = paginator.page(page)
        alert = ''
        if not article:
            alert = '搜索为空'
        return render(request, 'web/index.html', {'pages': pages, 'alert': alert, 'type': type, 'img':img})


def share(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        paginator = Paginator(articles, 20)
        pages = paginator.page(page)
        return render(request, 'web/share.html', {'pages': pages})


def info(request):
    if request.method == 'GET':
        types = AType.objects.all()
        page = int(request.GET.get('page', 1))
        articles = Article.objects.filter(is_show=1)
        paginator = Paginator(articles, 1)
        pages = paginator.page(page)
        return render(request, 'web/info.html', {'pages': pages, 'types': types, 'articles': articles})
    if request.method == 'POST':
        msg = request.POST.get('keyboard')
        types = AType.objects.all()
        article = Article.objects.filter(is_show=1, title__contains=msg)
        articles = Article.objects.filter(is_show=1)
        page = int(request.GET.get('page', 1))
        paginator = Paginator(article, 1)
        pages = paginator.page(page)
        alert = ''
        if not article:
            alert = '未搜索到文章'
        return render(request, 'web/info.html', {'pages': pages, 'types': types, 'articles': articles, 'alert': alert})

templates/backweb/add-category.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
</head>

<body>
</body>
</html>

templates/backweb/article.html
{% extends 'backweb/base_index.html' %}
{% block title %}
    article
{% endblock %}
{% block h1 %}
  操作
{% endblock %}
{% block right %}

<form action="" method="post" >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="{% url 'backweb:add_article' %}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{ pages.paginator.count }}</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                 <th><span class=""></span> <span class=""></span></th>
                   <th><span class="glyphicon "></span> <span class="visible-lg">图片</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            {% for page in pages %}
            <tbody>
              <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>
                <td class="article-title">{{ page.title }} </td>
                <td class="hidden-sm">{{ page.desc }}</td>
                  <td> {% if page.icon %}
                <img src="/media/{{ page.icon }}" alt="" width="20px" height="20px">
                {% endif %}</td>
                <td>{{ page.create_time }}
                </td>
                <td><a href="{% url 'backweb:edit_article' page.id %}">修改</a> <a rel="6" href="{% url 'backweb:del_article' page.id %}">删除</a></td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
                    {% if pages.has_previous %}
              <li><a href="{% url 'backweb:article' %}?page={{ pages.previous_page_number }}" aria-label="Previous" > <span aria-hidden="true">&laquo;</span> </a> </li>
                    {% endif %}
            {% for page in pages.paginator.page_range %}
              <li><a href="{% url 'backweb:article' %}?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
                    {% if pages.has_next %}
              <li><a href="{% url 'backweb:article' %}?page={{ pages.next_page_number }}" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
                    {% endif %}
            </ul>
          </nav>
        </footer>
      </form>

{% endblock %}

templates/backweb/index.html
{% extends 'backweb/base_index.html' %}
{% block title %}
    index
{% endblock %}
{% block h1 %}
    信息总览
{% endblock %}

templates/backweb/login.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/backweb/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/login.css">
<link rel="apple-touch-icon-precomposed" href="/static/backweb/images/icon/icon.png">
<link rel="shortcut icon" href="/static/backweb/images/icon/favicon.ico">
<script src="/static/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
    {% csrf_token %}
<div class="container">
  <div class="siteIcon"><img src="/static/backweb/images/icon/icon.png" alt="" data-toggle="tooltip" data-placement="top" title="欢迎使用异清轩博客管理系统" draggable="false" /></div>
  <form action="" method="post" autocomplete="off" class="form-signin">
    <h2 class="form-signin-heading">管理员登录</h2>
    <label for="userName" class="sr-only">用户名</label>
    <p style="color:red;padding-left:40%">{{ err_data }}</p>
    <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
    <label for="userPwd" class="sr-only">密码</label>
    <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
    <a href="main.html"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
  </form>
  <div class="footer">
    <p><a href="{% url 'backweb:register' %}" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">注册账号 →</a></p>
  </div>
</div>
<script src="/static/backweb/js/bootstrap.min.js"></script>
 <script type="text/javascript" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>
<script>
$('[data-toggle="tooltip"]').tooltip();
window.oncontextmenu = function(){
	//return false;
};
$('.siteIcon img').click(function(){
	window.location.reload();
});
$('#signinSubmit').click(function(){
	if($('#userName').val() === ''){
		$(this).text('用户名不能为空');
	}else if($('#userPwd').val() === ''){
		$(this).text('密码不能为空');
	}else{
		$(this).text('请稍后...');
	}
});
</script>
</body>
</html>

templates/web/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>博客首页</title>
<meta name="keywords" content="个人博客" />
<meta name="description" content="个人博客分享学习。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">古拉梅林个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'web:index' %}">网站首页</a></li>
      <li><a href="{% url 'web:share' %}">我的相册</a></li>
      <li><a href="##">我的日记</a></li>
      <li><a href="##">关于我</a></li>
      <li><a href="{% url 'web:info' %}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/web/images/4.jpg"></i>
          <p><b>古拉梅林</b>一个80后草根站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          {% for i in data %}
          <li><a href="/"><img src="/media/{{ i.icon }}"></a></li>
          {% endfor %}
          {% for i in img %}
          <li><a href="/"><img src="/media/{{ i.icon }}"></a></li>
          {% endfor %}
        </ul>
      </div>
      <div class="search">
        <form action="" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for i in type %}
          <li><a href="/">{{ i.types }}</a></li>
          {% endfor %}

        </ul>
      </div>
      <!--<div class="tuijian">-->
        <!--<h2>站长推荐</h2>-->
        <!--<ul>-->
          <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->

        <!--</ul>-->
      <!--</div>-->
      <!--<div class="links">-->
        <!--<h2>友情链接</h2>-->
        <!--<ul>-->
          <!--<a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>-->
        <!--</ul>-->
      <!--</div>-->
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/web/images/wx.png">
        </ul>
      </div>
  </aside>
  <main class="r_box">
    {% for i in data %}
    <li><i><a href="/"><img src="/media/{{ i.icon }}" alt=""></a></i>
      <h3><a href="/">{{ i.title }}</a></h3>
      <p>{{ i.content }}</p>
    </li>
    {% endfor %}
        {% for i in pages %}
    <li><i><a href="/"><img src="/media/{{ i.icon }}" alt=""></a></i>
      <h3><a href="/">{{ i.title }}</a></h3>
      <p>{{ i.content }}</p>
    </li>
    {% endfor %}
    <p>{{ alert }}</p>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">古拉梅林</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
 <script type="text/javascript" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>
</html>

templates/web/info.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/info.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav>
    <div class="logo"><a href="##">古拉梅林个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'web:index' %}">网站首页</a></li>
      <li><a href="{% url 'web:share' %}">我的相册</a></li>
      <li><a href="##">我的日记</a></li>
      <li><a href="##">关于我</a></li>
      <li><a href="{% url 'web:share' }">内容页</a></li>
    </ul>
  </nav>
</header>
<article>
  <aside class="l_box">
    <div class="search">
      <form action="" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        {% for type in types %}
        <li><a href="##">{{ type.types }}</a></li>
       {% endfor %}
      </ul>
    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>
      <ul>
        {% for article in articles %}
        <li><a href="">{{ article.title }}</a></li>
        {% endfor %}
      </ul>
    </div>

    <div class="cloud">
      <h2>标签云</h2>
      <ul>
        <a href="##">陌上花开</a> <a href="##">校园生活</a> <a href="##">html5</a> <a href="##">SumSung</a> <a href="##">青春</a> <a href="##">温暖</a> <a href="##">阳光</a> <a href="##">三星</a><a href="##">索尼</a> <a href="##">华维荣耀</a> <a href="##">三星</a> <a href="##">索尼</a>
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.png">
      </ul>
    </div>
  </aside>
  <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title">{{ alert }}</h3>
        {% for page in pages %}
        <h3 class="news_title">{{ page.title }}{{ alert }}</h3>

        <div class="bloginfo">
          <ul>
            <li class="lmname"><a href="/">古拉梅林</a></li>
            <li class="timer">时间：{{ page.create_time }}</li>
          </ul>
        </div>

        <div class="tags"><a href="##" target="_blank">个人博客</a> &nbsp;
        <div class="news_about"><strong>简介</strong>{{ page.desc }}</div>
        <div class="news_con"> <br>
          <br>
          {{ page.content }}
          <br>
          <img alt="" src="/media/{{ page.icon }}"><br>
          &nbsp; </div>

      </div>
      <div class="share">
        <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>
      </div>
      <div class="nextinfo">
        {% if pages.has_previous%}
        <p>上一篇：<a href="{% url 'web:info' %}?page={{ pages.previous_page_number }}">{{ page.title }}</a></p>
        {% endif %}
        {% if pages.has_next %}
        <p>下一篇：<a href="{% url 'web:info' %}?page={{ pages.next_page_number }}">{{ page.title }}</a></p>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="##" target="_blank">古拉梅林个人博客</a> <a href="/">蜀ICP备1234567号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
 <script type="text/javascript" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>

</body>
</html>

templates/web/share.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>古拉梅林</title>
<meta name="keywords" content="个人博客" />
<meta name="description" content="杨" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">古拉梅林个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'web:index' %}">网站首页</a></li>
      <li><a href="{% url 'web:share' %}">我的相册</a></li>
      <li><a href="##">我的日记</a></li>
      <li><a href="##">关于我</a></li>
      <li><a href="{% url 'web:info' %}">内容页</a></li>
    </ul>
</nav>
</header>
<article>
  <div class="picbox">

        {% for page in pages %}
      <ul>
      <li data-scroll-reveal="enter bottom over 1s" ><a href="/"><i><img src="/media/{{ page.icon }}"></i>
        <div class="picinfo">
          <h3>{{ page.title }}</h3>
          <span>{{ page.desc }}</span> </div>
        </a></li>
          <li data-scroll-reveal="enter bottom over 1s" ><a href="/"><i><img src="/media/{{ page.icon }}"></i>
        <div class="picinfo">
          <h3>{{ page.title }}</h3>
          <span>{{ page.desc }}</span> </div>
        </a></li>
            </ul>
        {% endfor %}

  </div>
  <div class="pagelist"><a class="allpage"><b>99</b></a>&nbsp;&nbsp;<a href="#" class="curPage">1</a>&nbsp;&nbsp;<a href="#" onclick="page(2)">2</a>&nbsp;&nbsp;<a href="#" onclick="page(3)">3</a>&nbsp;&nbsp;<a href="#" onclick="page(4)">4</a>&nbsp;&nbsp;<a href="#" onclick="page(5)">5</a>&nbsp;&nbsp;<a href="#" onclick="page(6)">6</a>&nbsp;&nbsp;<a href="#" onclick="page(7)">7</a>&nbsp;&nbsp;<a href="#" onclick="page(8)">8</a>&nbsp;&nbsp;<a href="#" onclick="page(9)">9</a>&nbsp;&nbsp;<a href="#" onclick="page(2)">下一页</a></div>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">古拉梅林</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
 <script type="text/javascript" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>

</body>
</html>